### ISSUE TITLE
"Access is denied." Error Code 11 @ HealthVault - Your Web Service - Your Client Apps

### ISSUE THREAD

**Issue by SaaShah** [Microsoft/healthvault-samples#1]
Hi,

I'm using 'HealthVault - Your Web Service - Your Client Apps' code. I followed this guide ; https://blogs.msdn.microsoft.com/healthvault/2013/06/02/healthvault-your-web-service-your-client-apps/.

My application is registered and showing up @ https://config.healthvault-ppe.com/default.aspx.

I've checked all options in METHODS, ONLINE RULES and OFFLINE RULES. My certificate is also showing up at PUBLIC CERTS.

**I still get "Access is denied." Error Code 11 (HVDataAccess > GetThings).**

I've allowed the application as a user as well.

Am I missing a step or something ?

**Comment by jhutchings1** [comment]
Hi @SaadBinShahid, 
Can you confirm that your ApplicationId is set properly in the app source code?

**Comment by SaaShah** [comment]
Hi @jhutchings1,


Thank you so much for getting back to me. Yes, my applicationId is set.

```
public static class AppSettings
public static Guid ApplicationId() { return (new Guid("My AppID here!")); }
```

I've the same ID in my SDK, and the same App is pushed to my account. Do I've to set the AppID somewhere else ?

**Comment by jhutchings1** [comment]
Hi @SaadBinShahid, 
I ran through the instructions this morning on my side and I wasn't able to reproduce the issue you reported. Can you provide me more details about your repro and exactly what fails?
