### ISSUE TITLE
Possible to not use MSFT Accounts? 

### ISSUE THREAD

**Issue by ExperimentsAndIdeas** [Microsoft/healthvault-samples#20]
I have a pre-existing OpenID Connect/OAuth directory with several patients and doctors interested in using HealthVault. 

Is there any way HealthVault can use AzureAD, or something other than a MSFT account?

**Comment by jhutchings1** [comment]
Hi @makerofthings7, we don't have that functionality right now, but I'd love to talk more about your scenarios to understand how we can help out. Please email hvtech@microsoft.com and we can discuss in more depth. 
Thanks!
