### ISSUE TITLE
IN HealthVaultProviderManagementPortal sample getting as  REST call failed 

### ISSUE THREAD

**Issue by manjulag** [Microsoft/healthvault-samples#9]

**Comment by RandomEngy** [comment]
Can you give some more details? What was the status code and content of the failed call? What were you trying to do?

**Comment by manjulag** [comment]
Hello David,
Am  trying HealthVaultProviderManagementPortal sample code here am able to
create and send an invitation but am not be able to create Action plan
,when i click on online to setup and edit action plans i will be getting as
API call failed

Response status code: Unauthorized

Response body:
Have set my application id in web config file in debugging i came to know
that person Id and record Id is null
i just need guidance where am going wrong and in my country health
vault insights app is not available is this a reason for getting error?



Thanking You,
Manjula G

**Comment by jhutchings1** [comment]
Hi Manjula,  
> in my country healthvault insights app is not available is this a reason for getting error?
Yes, this is the root cause for the error you described. 

Sorry for the difficulty, we will be sure to announce any changes to our supported regions via the HealthVault developer blog. https://blogs.msdn.microsoft.com/healthvault/ 

Thanks!
Justin
